# build environment
FROM node:20.10.0-alpine as build
WORKDIR /app
RUN npm install -g pnpm
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install
COPY . ./
RUN pnpm build:staging1

# production environment
FROM nginx:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
