export default {
  title:
    'Solutions open-source pour <strong>réhumaniser</strong> et <strong>dépolariser</strong> le paysage social en ligne.\n\nPour un monde plus inclusif et démocratique.',
  getInTouch: 'Rejoignez la communauté',
  buildingAgora: 'Nous développons <strong>Agora</strong>, un <a href="https://en.wikipedia.org/wiki/Wiki_survey" target="_blank">wiki de sondages collaboratifs</a> open-source visant à améliorer la <i>participation civique</i> ainsi qu\'à lutter contre la <i>censure</i> et la <i>propagande computationnelle</i>, et ce d\'une manière respectueuse de la vie privée des participants.',
  whatIsCompPropaganda: 'La propagande computationnelle se réfère à "l\'utilisation d\'algorithmes, d\'automatisation et de curation humaine pour distribuer intentionnellement des informations trompeuses sur les réseaux sociaux" (Woolley & Howard, 2018). Elle exacerbe les divisions sociétales, crée des confusions et manipule les résultats électoraux, sapant ainsi les démocraties.',
  coreInnovationTitle: 'Notre innovation principale',
  coreInnovationPart1: 'Nous avons développé un <a href="https://github.com/zkorum/poc/blob/main/vc-flow/README.md" target="_blank">protocole de publication vérifiable et respectueux de la vie privée</a>, basé sur un standard émergent de certificat digital bientôt utilisé en UE appelé "Verifiable Credentials" et sur la "preuve sans divulgation d\'information" aussi appelé "Zero Knowledge Proof (ZKP)", qui permet aux utilisateurs de contrôler de manière granulaire leurs identités et données sur les réseaux sociaux. Cette solution non seulement résiste aux bots et faux comptes mais maximise également la vie privée des utilisateurs.',
  coreInnovationPart2: 'Par exemple, si quelqu\'un créé une publication en tant que citoyen français anonyme, nous pouvons prouver cryptographiquement que ce post provient bien d\'un utilisateur unique avec une carte d\'identité française, bien que nous ne sachions pas qui est cette personne. L\'origine de chaque publication est chiffrée côté client (appareil de l\'utilisateur) empêchant quiconque de relier les posts à leurs auteurs.',
  otherBuildingBlocksTitle: 'Autres piliers technologiques',
  otherBuildingBlocksPart1: 'Infrastructure minimisant le besoin de confiance afin de fournir une modération auditable',
  otherBuildingBlocksPart2: 'Algorithmes de classement des publications des utilisateurs dont l\'objectif est la dépolarisation ("Bridging-based ranking algorithms") pour identifier et promouvoir les voix qui rassemblent (opinions partagées par des utilisateurs de bords politiques différents), par opposition aux algorithmes basés sur l\'engagement qui sont connus pour alimenter les polarisations',
  teamTitle: 'Notre équipe',
  yutingDescription: 'Profondément passionnée par l\'intersection des technologies et des sciences sociales, Yuting est une entrepreneure créative avec un parcours multiculturel et interdisciplinaire.<br /><br />Parlant couramment l\'anglais, le chinois, et le français, elle a été cadre commercial chez Microsoft France, menant des négociations sur des contrats à sept chiffres avec des clients B2B. Elle a un diplôme de cinéma de l\'Université de New York Abu Dhabi et un Master en Management de l\'ESSEC Business School.',
  nicolasDescription: 'Diplômé de l\'IMT Atlantique, Nicolas est un ingénieur logiciel full-stack naturellement curieux avec dix ans d\'expérience. Fervent défenseur des logiciels libres, il est motivé par l\'utilisation éthique des technologies digitales permettant aux humains de faire plus et mieux que dans la vie réelle.<br /><br />Précédemment architecte logiciel dans le réseau Protocol Labs, un écosystème de startups innovantes poussant des avancées majeures dans l\'informatique, Nicolas a développé une expertise en cryptographie appliquée et en solutions Web décentralisées.',
  featuredIn: 'ZKorum dans la presse',
  about: 'Documentation'
};

