FROM node:20.10.0-alpine
WORKDIR /app
RUN npm install -g pnpm
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install
COPY . ./
RUN pnpm build

# Install Python and pip
RUN apk add --no-cache python3 python3-dev py3-pip

# Copy requirements.txt and install Python packages
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY src/python /zkorum

EXPOSE 8080
CMD ["pnpm", "start"]
